### PR TITLE
Added Resource Policy for sqs Queue

### PR DESCRIPTION
**Pull request by Patelvijaykumar**

### CODE REVIEW

**Comment by antonbabenko** [comment]
Hi Vijay!

Thank you for the contribution.

I am not sure whether this PR is complete and should be reviewed in details because:

1. It creates IAM resources, which is not the purpose for such SQS resource module.
1. It does not putting created policy as a parameter to the created SQS queue resource. Consider using [aws_sqs_queue_policy](https://www.terraform.io/docs/providers/aws/r/sqs_queue_policy.html) resource for that.

BR,
Anton.

**Comment by Patelvijaykumar** [comment]
Hi Anton,

Thanks for your replay.

we observed that every resource need policy when it used by another resource like ecs and with the resource policy user needs to attached resource policy with relevant resource IAM role. So basically resource policy should get create with a resource.

Many Thanks,
Vijay

**Comment by antonbabenko** [comment]
If you need to create IAM policy you can do this outside of this resource module. This module currently is missing the possibility to connect IAM policy with SQS queue - this is what `aws_sqs_queue_policy` resource for.

**Comment by antonbabenko** [comment]
I disagree, efficiency is not gained by mixing them in one module. Sorry, I have to close this one.

**Pull request closed without merging**
