### PR TITLE
chore: add examples validation ci/cd workflow

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- add 2nd CI/CD workflow to extract version from each `examples/` directory and perform `terraform validate` on that example

## Motivation and Context
- the `pre-commit` workflow is executed from the project root directory and handles everything (linting, validation, formatting, docs, etc.), but it utilizes the version specified in the root directory. to be a bit more exhaustive with the checks, a 2nd workflow is added here that will extract the versions set in each `examples/` directory and perform just validation on that directory

## Breaking Changes
- No - CI/CD checks only

## How Has This Been Tested?
- See results of checks on PR

### CODE REVIEW

**Comment by bryantbiggs** [comment]
@antonbabenko looks to be working 👍🏼 - I'll open PRs for the rest of the repos later today. getting caught up on `todos` over the holiday break!

**Comment by antonbabenko** [comment]
Yes, looks very good!

I am looking into the workflow file and wonder what does `directory: [examples/complete, examples/simple]` mean there? Will it try to find the version range in those directories? Should we include root dir also? Should it be just a root dir or a module dir recursively (eg, [IAM module consist of several submodules](https://github.com/terraform-aws-modules/terraform-aws-iam))?

Feel free to send small updates in other repos one by one during the holiday break ([IAM module](https://github.com/terraform-aws-modules/terraform-aws-iam) can be a good next case).

Thank you very much for your work!

**Comment by bryantbiggs** [comment]
@antonbabenko thats a good point, I took a 2nd look and had a few things to correct plus I've updated this PR to not just be a "testing" PR but to actually add a 2nd workflow for performing an extra step of validation on the `examples/` directories. So the high level steps of what is happening now in this PR is:

1. The `pre-commit` workflow is executed at the root of the project
	- The minimum and maximum versions are extracted from the project root
	- The pre-commit hooks are executed on the entire project from the root of the project (i.e - `pre-commit run -a`) using both the minimum and maximum supported Terraform version identified
2. The `examples` workflow is executed from each of the directories under the `examples/` directory
	- The minimum and maximum versions are extracted from the example sub-directory
	- `terraform init -backend=false && terraform validate` are executed for both the minimum and maximum supported Terraform version identified for the example sub-directory
	
So the `pre-commit` workflow handles the entire project where the `examples` workflow is just checking the validity of the configuration files for each example sub-directory since the `pre-commit` workflow already handled the linting, documentation, etc.

**Comment by antonbabenko** [comment]
In the IAM module, I recommend just merge two workflows into one - pre-commit hooks already do everything good. :)

We need to run `pre-commit run -a` (as you already do) for unique min and max versions identified in each folder (examples, modules, root).

**Comment by bryantbiggs** [comment]
but pre-commit runs more checks than we need for each module/example (i.e. - linting, documentation, formatting). we really only need to checking formatting, linting, and documentation once (at the project root) - validation is the only command we need to run in each module and each example

**Comment by antonbabenko** [comment]
We need to make sure that all code is still good and not just examples. Running `pre-commit run -a` from the root will verify everything (including, `terraform validate` in all folders where tf-files are and not just in examples).

**Comment by bryantbiggs** [comment]
correct - my thought process was:
1. we need to check the entire project for code formatting, linting, and documentation - which pre-commit handles
2. we need to validate the root module with the min/max terraform version specified - which pre-commit handles
3. we need to validate the `examples/` provided in the project with the min/max terraform version specified - which pre-commit does NOT handle. pre-commit uses the terraform min/max versions set at the project root and does not respect the version set in the `examples/` directory (to the best of my understanding)
4. we need to validate the `modules/` provided in the project (if any) with the min/max terraform version specified - again, pre-commit does NOT handle this as it does not respect the individual sub-module versions

this is why I say that pre-commit cannot handle all cases since:
1. it doesn't make sense to re-run the format, lint, and documentation checks for each example project and each sub-module
2. running pre-commit from the project root does not pick up any differences if the versions specified in the `examples/` or `modules/` are different from that of the project root. if these should always be in sync then thats a different story and we could remove the `versions.tf` from the `examples/` if that is the case

**Comment by antonbabenko** [comment]
3&4. In fact, there is no difference between examples, modules, root, and other directories to process as long as there are tf-files inside. All should be valid for checks to pass. We can make it to use root version requirements (if found) when running pre-commit, right? If not in root, then in modules?

Versions of Terraform are very similar and I don't think we will have a lot of issues with it but versions of providers are handled by pre-commit hooks (eg, `terraform_validate`) which will install correct versions per directory.

Further:
1. Docs, linting is rather unnecessary but it will/should produce the same result when running with different versions. If this is not the case, we can limit to run just one hook (eg, `terraform_validate`)
2. The reason why `versions.tf` is everywhere (and `variables.tf` is sometimes empty) it to pass tflint rules. In theory they can be different, but in practice the main versions.tf is in the root or in submodules.

**Comment by bryantbiggs** [comment]
I guess I am confused - I'm not sure why we are forcing `pre-commit` onto everything since its for executing hooks before making a commit, not necessarily a catch-all for everything - CI/CD included. but I guess for now, we will just run pre-commit at the project root and thats it

**Comment by antonbabenko** [comment]
Let's get back to this and the rest of our work after the holidays!

Thanks again for your work on all the stuff (including GH actions)!

Merry Christmas! 🎄  🎁  🎅

**Comment by antonbabenko** [comment]
I trust you on this very much! Let's get this merged and apply it to a couple more much active repositories (Lambda and Autoscaling) to see if what I said previously even makes sense.

**Pull request merged**
